---
SWITCH-A:
  hostname: switch-a.company.x
  groups:
    - SWITCH
    - PROD
    - BUILDING-A
  data:
    loc: Building-A, Floor-1, Room-999
  platform: cisco_ios

ROUTER-A:
  hostname: router-a.company.x
  groups:
    - ROUTER
    - PROD
    - BUILDING-A
  data:
    loc: Building-A, Floor-1, Room-111
  platform: cisco_nxos

SWITCH-X:
  hostname: switch-x.company.x
  groups:
    - SWITCH
    - DEV
    - BUILDING-B
  data:
    loc: Building-B, Floor-9, Room-111
  platform: cisco_ios

ROUTER-Q:
  hostname: router-q.company.x
  groups:
    - ROUTER
    - DEV
    - BUILDING-B
  data:
    loc: Building-B, Floor-5, Room-555
  platform: cisco_nxos
